version: '3.3'

services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'agrologistics'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3308:3306
    networks:
      net:
        ipv4_address: 172.20.0.2  
  api:
    container_name: api
    build: ./API/
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 8080:8080
    links:
      - db
    networks:
      net:
        ipv4_address: 172.20.0.3  
networks:
  net:
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: 172.20.0.0/16